# Общие настройки, применяемые ко всем профилям
server:
  port: 8080

logging:
  level:
    root: ERROR
    org:
      springframework: ERROR

spring:
  main:
    banner-mode: off
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

---
# Профиль prod
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/ewm_db
    driverClassName: org.postgresql.Driver
    username: dbuser
    password: 12345
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          timezone: UTC
  
  sql:
    init:
      mode: always

---
# Профиль test
logging:
  level:
    root: ERROR
    org:
      springframework: ERROR

spring:
  config:
    activate:
      on-profile: test

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ewm_db;MODE=MySQL
    username: dbuser
    password: 12345

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console