services:
  stats-server:
    build: ./stats/server
    image: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat_db
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
  stats-db:
    image: postgres:16.1
    ports:
      - "6666:5432"
    container_name: stats-db
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  ewm-server:
    build: ./main-service
    image: ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
  ewm-db:
    image: postgres:16.1
    ports:
      - "6665:5432"
    container_name: ewm-db
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
