services:
  stats-server:
    build: ./stats/server
    image: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STAT_URL_DB=jdbc:postgresql://state_server-db:5432/stat_db
      - STAT_USERNAME_DB=dbuser
      - STAT_PASSWORD_DB=12345

  stats-db:
    image: postgres:16.1
    container_name: stats-server-db
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

