services:
  stats-server:
    build: ./stats/server
    image: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://server-db:5432/stat_db
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: server-db
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

